<script setup lang="ts">
import AcademicNav from '@/Components/AcademicNav.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { formatDateOnly } from '@/Support/dateOnly';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

const props = defineProps<{ source: any; links: any[]; linkChoices: Record<string, any[]>; courseChoices: Record<string, any[]>; courseDefaults: Record<string, any>; permissions: Record<string, boolean>; reviewTransitions: string[] }>();
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const reviewForm = useForm({ review_status: '' });
const linkType = ref(Object.keys(props.linkChoices)[0] ?? '');
const linkForm = useForm({ link_type: linkType.value, link_id: null as number | null });
const fileForm = useForm({ source_file: null as File | null });
const courseForm = useForm<any>({ ...props.courseDefaults, code: '', status: 'draft' });
const currentChoices = computed(() => props.linkChoices[linkType.value] ?? []);
const canDraftCalendar = computed(() => props.source.review_status === 'reviewed' && props.source.source_category === 'calendar' && props.permissions.manage);
const canDraftCurriculum = computed(() => props.source.review_status === 'reviewed' && ['curriculum', 'pacing', 'scope_and_sequence'].includes(props.source.source_category) && props.permissions.manage);
const canDraftCourse = computed(() => props.source.review_status === 'reviewed' && ['course_guide', 'curriculum'].includes(props.source.source_category) && props.permissions.manage);
const changeReview = () => {
    if (reviewForm.review_status === 'rejected' && !window.confirm('Reject this source? It will remain available as historical evidence.')) return;
    reviewForm.patch(route('academic.sources.review', props.source.id), { preserveScroll: true, onSuccess: () => reviewForm.reset() });
};
const addLink = () => { linkForm.link_type = linkType.value; linkForm.post(route('academic.sources.links.store', props.source.id), { preserveScroll: true, onSuccess: () => linkForm.reset('link_id') }); };
const replaceFile = (event: Event) => { fileForm.source_file = (event.target as HTMLInputElement).files?.[0] ?? null; };
const upload = () => fileForm.post(route('academic.sources.files.store', props.source.id), { forceFormData: true, preserveScroll: true, onSuccess: () => fileForm.reset() });
const archive = () => { if (window.confirm('Archive this source? Its history and files will be preserved.')) router.patch(route('academic.sources.archive', props.source.id)); };
</script>

<template><Head :title="source.title" /><AuthenticatedLayout>
    <div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h1 class="h2 mb-1">{{ source.title }}</h1><p class="text-secondary mb-0">{{ label(source.source_category) }} · {{ label(source.source_kind) }} · {{ label(source.authority_level) }}</p></div><div class="d-flex gap-2"><Link class="btn btn-outline-secondary" :href="route('academic.sources.index')">Back</Link><Link v-if="permissions.manage && !source.archived_at" class="btn btn-outline-primary" :href="route('academic.sources.edit', source.id)">Edit</Link></div></div><AcademicNav />
    <div v-if="source.archived_at" class="alert alert-secondary">Archived {{ new Date(source.archived_at).toLocaleString() }}. This source is retained as historical evidence.</div>
    <div class="row g-4"><div class="col-lg-8">
        <section class="card mb-4"><div class="card-body"><div class="d-flex justify-content-between"><h2 class="h5">Source record</h2><span class="badge text-bg-light border">{{ label(source.review_status) }}</span></div>
            <p v-if="source.description" class="text-pre-wrap">{{ source.description }}</p><dl class="row mb-0"><dt class="col-sm-4">Provider</dt><dd class="col-sm-8">{{ source.education_provider?.name ?? 'Not specified' }}</dd><dt class="col-sm-4">School year</dt><dd class="col-sm-8">{{ source.school_year?.name ?? source.academic_year_label ?? 'Not specified' }}</dd><dt class="col-sm-4">Grade</dt><dd class="col-sm-8">{{ source.grade_level?.name ?? 'Not specified' }}</dd><dt class="col-sm-4">Version</dt><dd class="col-sm-8">{{ source.version_label ?? 'Not specified' }}</dd><dt class="col-sm-4">Publication date</dt><dd class="col-sm-8">{{ source.publication_date ? formatDateOnly(source.publication_date) : 'Not specified' }}</dd><template v-if="source.source_kind === 'url'"><dt class="col-sm-4">Stored URL</dt><dd class="col-sm-8"><a :href="source.source_url" target="_blank" rel="noopener noreferrer nofollow">{{ source.source_url }}</a><div class="small text-secondary">Stored reference only; not fetched by the application.</div></dd></template><dt class="col-sm-4">Processing</dt><dd class="col-sm-8">{{ label(source.processing_status) }}</dd></dl>
            <div v-if="source.notes" class="mt-3"><h3 class="h6">Internal notes</h3><p class="mb-0 text-pre-wrap">{{ source.notes }}</p></div>
        </div></section>
        <section class="card mb-4"><div class="card-body"><h2 class="h5">Private file versions</h2><p v-if="source.source_kind !== 'upload'" class="text-secondary mb-0">This source does not use uploaded files.</p><div v-else-if="!source.files.length" class="text-secondary">No file is stored.</div><div v-else class="table-responsive"><table class="table align-middle"><thead><tr><th>Version</th><th>Original filename</th><th>Size</th><th>Checksum</th><th></th></tr></thead><tbody><tr v-for="file in source.files" :key="file.id"><td>v{{ file.version_number }} <span v-if="file.is_current" class="badge text-bg-primary">Current</span></td><td>{{ file.original_filename }}<div class="small text-secondary">{{ file.mime_type }}</div></td><td>{{ Math.ceil(file.file_size / 1024) }} KB</td><td><code>{{ file.checksum_sha256.slice(0, 12) }}…</code></td><td><a v-if="permissions.download" class="btn btn-sm btn-outline-primary" :href="route('academic.sources.files.download', [source.id, file.id])">Download</a></td></tr></tbody></table></div></div>
            <form v-if="permissions.manage && source.source_kind === 'upload' && !source.archived_at" class="card-footer bg-white" @submit.prevent="upload"><label for="replacement-file" class="form-label">Upload replacement version</label><div class="d-flex gap-2"><input id="replacement-file" class="form-control" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.docx,.xlsx,.csv,.txt" required @change="replaceFile"><button class="btn btn-outline-primary" :disabled="fileForm.processing">Upload</button></div><div v-if="fileForm.errors.source_file" class="invalid-feedback d-block">{{ fileForm.errors.source_file }}</div></form>
        </section>
        <section class="card"><div class="card-body"><h2 class="h5">Linked academic records</h2><p v-if="!links.length" class="text-secondary">No academic records linked.</p><ul v-else class="list-group list-group-flush"><li v-for="item in links" :key="item.id" class="list-group-item px-0 d-flex justify-content-between"><span><span class="text-capitalize">{{ label(item.type) }}</span>: {{ item.label }}</span><Link v-if="permissions.manage && !source.archived_at" as="button" method="delete" class="btn btn-sm btn-link text-danger" :href="route('academic.sources.links.destroy', [source.id, item.id])" preserve-scroll>Remove</Link></li></ul></div>
            <form v-if="permissions.manage && !source.archived_at" class="card-footer bg-white" @submit.prevent="addLink"><div class="row g-2"><div class="col-md-5"><label for="link-type" class="form-label">Record type</label><select id="link-type" v-model="linkType" class="form-select" @change="linkForm.link_id = null"><option v-for="(_, type) in linkChoices" :key="type" :value="type">{{ label(String(type)) }}</option></select></div><div class="col-md-5"><label for="link-target" class="form-label">Record</label><select id="link-target" v-model="linkForm.link_id" class="form-select" required><option :value="null">Select record</option><option v-for="choice in currentChoices" :key="choice.id" :value="choice.id">{{ choice.label }}</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary w-100" :disabled="linkForm.processing">Link</button></div></div><div v-if="linkForm.errors.link_id || linkForm.errors.link_type" class="invalid-feedback d-block">{{ linkForm.errors.link_id || linkForm.errors.link_type }}</div></form>
        </section>
    </div><aside class="col-lg-4">
        <section v-if="permissions.review && !source.archived_at" class="card card-body mb-4"><h2 class="h5">Review</h2><form v-if="reviewTransitions.length" @submit.prevent="changeReview"><label for="review-transition" class="form-label">Move to</label><select id="review-transition" v-model="reviewForm.review_status" class="form-select mb-2" required><option value="">Select status</option><option v-for="status in reviewTransitions" :key="status" :value="status">{{ label(status) }}</option></select><button class="btn btn-primary" :disabled="reviewForm.processing">Update review</button></form><p v-else class="text-secondary mb-0">No further review transitions are available.</p></section>
        <section v-if="permissions.manage && !source.archived_at" class="card card-body mb-4"><h2 class="h5">Structured drafts</h2><p class="small text-secondary">These actions create an empty draft linked to this reviewed source. They never extract or publish data automatically.</p><Link v-if="canDraftCalendar" as="button" method="post" class="btn btn-outline-primary mb-2" :href="route('academic.sources.draft-calendar', source.id)">Create calendar draft</Link><Link v-if="canDraftCurriculum" as="button" method="post" class="btn btn-outline-primary mb-2" :href="route('academic.sources.draft-curriculum', source.id)">Create curriculum draft</Link><form v-if="canDraftCourse" @submit.prevent="courseForm.post(route('academic.sources.draft-course', source.id))"><hr><h3 class="h6">Create course draft</h3><select v-model="courseForm.subject_id" class="form-select mb-2" aria-label="Subject" required><option :value="null">Select subject</option><option v-for="item in courseChoices.subjects" :key="item.id" :value="item.id">{{ item.name }}</option></select><input v-model="courseForm.name" class="form-control mb-2" aria-label="Course name" required><input v-model="courseForm.code" class="form-control mb-2" aria-label="Course code" placeholder="Course code" required><div class="row g-2 mb-2"><div class="col-6"><select v-model="courseForm.minimum_grade_level_id" class="form-select" aria-label="Minimum grade"><option :value="null">No minimum grade</option><option v-for="item in courseChoices.gradeLevels" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><div class="col-6"><select v-model="courseForm.maximum_grade_level_id" class="form-select" aria-label="Maximum grade"><option :value="null">No maximum grade</option><option v-for="item in courseChoices.gradeLevels" :key="item.id" :value="item.id">{{ item.name }}</option></select></div></div><select v-model="courseForm.education_provider_id" class="form-select mb-2" aria-label="Education provider"><option :value="null">No provider</option><option v-for="item in courseChoices.providers" :key="item.id" :value="item.id">{{ item.name }}</option></select><select v-model="courseForm.standards_framework_id" class="form-select mb-2" aria-label="Standards framework"><option :value="null">No standards framework</option><option v-for="item in courseChoices.frameworks" :key="item.id" :value="item.id">{{ item.name }}</option></select><textarea v-model="courseForm.description" class="form-control mb-2" aria-label="Course description" rows="3"></textarea><button class="btn btn-outline-primary" :disabled="courseForm.processing">Create course draft</button><div v-if="Object.keys(courseForm.errors).length" class="invalid-feedback d-block">{{ Object.values(courseForm.errors)[0] }}</div></form><p v-if="source.review_status !== 'reviewed'" class="text-secondary mb-0">Complete review before creating a draft.</p></section>
        <button v-if="permissions.manage && !source.archived_at" class="btn btn-outline-danger" type="button" @click="archive">Archive source</button>
    </aside></div>
</AuthenticatedLayout></template>
