<script setup lang="ts">
import AcademicNav from '@/Components/AcademicNav.vue'; import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import { Head, Link, useForm } from '@inertiajs/vue3';
const props = defineProps<{ framework?: any; providers: any[] }>(); const form = useForm({ education_provider_id: props.framework?.education_provider_id ?? null, name: props.framework?.name ?? '', short_name: props.framework?.short_name ?? '', jurisdiction: props.framework?.jurisdiction ?? '', version_label: props.framework?.version_label ?? 'unversioned', effective_start_date: props.framework?.effective_start_date ?? '', effective_end_date: props.framework?.effective_end_date ?? '', status: props.framework?.status ?? 'draft', source_url: props.framework?.source_url ?? '', notes: props.framework?.notes ?? '' }); const submit=()=>props.framework?form.patch(route('academic.standards.update',props.framework.id)):form.post(route('academic.standards.store'));
</script>
<template><Head :title="framework ? 'Edit Standards Framework' : 'Add Standards Framework'" /><AuthenticatedLayout><h1 class="h2">{{ framework ? 'Edit custom framework' : 'Add custom framework' }}</h1><AcademicNav /><form class="card" @submit.prevent="submit"><div class="card-body"><div class="row g-3">
<div class="col-md-8"><label for="framework-name" class="form-label">Name</label><input id="framework-name" v-model="form.name" class="form-control" required><div v-if="form.errors.name" class="invalid-feedback d-block">{{ form.errors.name }}</div></div><div class="col-md-4"><label for="framework-short" class="form-label">Short name</label><input id="framework-short" v-model="form.short_name" class="form-control"></div>
<div class="col-md-4"><label for="framework-version" class="form-label">Version label</label><input id="framework-version" v-model="form.version_label" class="form-control" required></div><div class="col-md-4"><label for="framework-jurisdiction" class="form-label">Jurisdiction</label><input id="framework-jurisdiction" v-model="form.jurisdiction" class="form-control"></div><div class="col-md-4"><label for="framework-status" class="form-label">Status</label><select id="framework-status" v-model="form.status" class="form-select"><option v-for="s in ['draft','active','retired','archived']" :key="s">{{s}}</option></select></div>
<div class="col-md-6"><label for="framework-provider" class="form-label">Provider</label><select id="framework-provider" v-model="form.education_provider_id" class="form-select"><option :value="null">No provider</option><option v-for="p in providers" :key="p.id" :value="p.id">{{p.name}}{{p.tenant_id===null?' (shared)':''}}</option></select></div><div class="col-md-6"><label for="framework-url" class="form-label">Source URL</label><input id="framework-url" v-model="form.source_url" type="url" class="form-control"></div>
<div class="col-md-6"><label for="framework-start" class="form-label">Effective start</label><input id="framework-start" v-model="form.effective_start_date" type="date" class="form-control"></div><div class="col-md-6"><label for="framework-end" class="form-label">Effective end</label><input id="framework-end" v-model="form.effective_end_date" type="date" class="form-control"></div><div class="col-12"><label for="framework-notes" class="form-label">Notes</label><textarea id="framework-notes" v-model="form.notes" class="form-control" /></div>
</div></div><div class="card-footer bg-white text-end"><Link class="btn btn-outline-secondary me-2" :href="route('academic.standards.index')">Cancel</Link><button class="btn btn-primary" :disabled="form.processing">Save framework</button></div></form></AuthenticatedLayout></template>
