<script setup lang="ts">
import StudentPortalLayout from '@/Layouts/StudentPortalLayout.vue';
import MiniStoryGoal from '@/Components/MiniStoryGoal.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import axios from 'axios';
import { computed, onBeforeUnmount, ref, watch } from 'vue';
const props=defineProps<{entry:any;history_url:string;autosave_url:string;submit_url:string}>();
const form=useForm({response:props.entry.response||''});const saveState=ref(props.entry.last_saved_at?'All changes saved':'Ready to write');const checks=ref(props.entry.story_check);let timer:ReturnType<typeof setTimeout>|undefined;
const wordCount=computed(()=>form.response.trim()?form.response.trim().split(/\s+/).length:0);const submitted=computed(()=>props.entry.status==='submitted');
const saveDraft=async(response:string)=>{try{const result=await axios.patch(props.autosave_url,{response});checks.value=result.data.story_check;saveState.value='All changes saved';}catch{saveState.value='Could not save yet—keep this page open and try again.';}};
watch(()=>form.response,()=>{if(submitted.value)return;if(timer)clearTimeout(timer);saveState.value='Saving…';const response=form.response;timer=setTimeout(()=>void saveDraft(response),650);});
onBeforeUnmount(()=>{if(timer){clearTimeout(timer);void saveDraft(form.response);}});const submit=()=>{if(timer)clearTimeout(timer);form.post(props.submit_url,{preserveScroll:true});};
</script>
<template><Head :title="entry.title"/><StudentPortalLayout><Link class="back-link" :href="history_url">← My Story Archive</Link><article class="writing-shell"><header><p>Today’s Writing Mission · {{ entry.date }}</p><h1>{{ entry.title }}</h1><span v-if="entry.category">{{ entry.category }}</span></header><section class="prompt-panel"><p>{{ entry.prompt }}</p><h2>Include:</h2><ul><li v-for="hint in entry.include_hints" :key="hint">{{ hint }}</li></ul><MiniStoryGoal /></section><section class="editor-panel"><div class="editor-bar"><strong>{{ submitted?'Submitted Story':'Mission Draft' }}</strong><span>{{ wordCount }} words · {{ saveState }}</span></div><textarea id="story-editor" v-model="form.response" :readonly="submitted" rows="19" aria-label="Creative writing response" placeholder="Begin your story here…"/><p v-if="form.errors.response" class="error" role="alert">{{ form.errors.response }}</p></section><section class="story-check"><div><p>Supportive revision guide</p><h2>Story Check</h2><span>These suggestions never block submission.</span></div><ul><li v-for="check in checks" :key="check.key" :class="{passed:check.passed}"><span>{{ check.passed?'✓':'!' }}</span><div><strong>{{ check.label }}</strong><p>{{ check.message }}</p></div></li></ul></section><div v-if="!submitted" class="submit-row"><a class="btn btn-outline-primary" href="#story-editor">Improve My Story</a><button class="btn btn-warning fw-bold" type="button" :disabled="form.processing" @click="submit">Submit Journal</button></div><div v-else class="submitted-banner">Mission submitted on {{ entry.submitted_at }}. Your story is preserved.</div><aside v-if="entry.teacher_feedback" class="feedback"><strong>Teacher/parent feedback</strong><p>{{ entry.teacher_feedback }}</p></aside></article></StudentPortalLayout></template>
<style scoped>.back-link{display:inline-block;margin-bottom:1rem;font-weight:800}.writing-shell{display:grid;gap:1.25rem;max-width:980px;margin:auto}.writing-shell>header{padding:1.5rem;border-radius:1.3rem;background:linear-gradient(135deg,#392f78,#65549c);color:#fff}.writing-shell>header p{text-transform:uppercase;letter-spacing:.12em;font-size:.75rem;font-weight:900}.writing-shell>header h1{font-size:clamp(2rem,5vw,3.2rem)}.writing-shell>header span{display:inline-block;border-radius:99px;background:#ffffff25;padding:.3rem .7rem}.prompt-panel,.editor-panel,.story-check,.feedback{border:1px solid #dbe5eb;border-radius:1.2rem;background:#fff;padding:1.3rem;box-shadow:0 8px 22px #17324d10}.prompt-panel>p{font-size:1.15rem;line-height:1.7}.prompt-panel h2{font-size:1rem}.prompt-panel ul{display:flex;flex-wrap:wrap;gap:.45rem;padding:0;list-style:none}.prompt-panel li{border-radius:99px;background:#edf5f8;padding:.35rem .7rem}.prompt-panel details{padding:.9rem;border-radius:.8rem;background:#fff6d9}.prompt-panel summary{font-weight:900;cursor:pointer}.prompt-panel details div{padding-top:.6rem}.editor-panel{padding:0;overflow:hidden}.editor-bar{display:flex;justify-content:space-between;gap:1rem;padding:.8rem 1rem;background:#e9f3f2;color:#31505e}.editor-panel textarea{display:block;width:100%;border:0;resize:vertical;padding:1.4rem;font:1.05rem/1.8 Georgia,serif;color:#263d4d;outline:none}.editor-panel textarea:focus{box-shadow:inset 0 0 0 3px #efbd52}.error{margin:0;padding:.7rem 1rem;background:#fde4dd;color:#762d1b}.story-check>div>p{text-transform:uppercase;letter-spacing:.1em;font-size:.72rem;font-weight:900;color:#6c5993;margin:0}.story-check ul{display:grid;grid-template-columns:repeat(2,1fr);gap:.7rem;padding:0;list-style:none;margin:1rem 0 0}.story-check li{display:flex;gap:.7rem;padding:.8rem;border-radius:.8rem;background:#fff2e9}.story-check li>span{display:grid;place-items:center;flex:none;width:28px;height:28px;border-radius:50%;background:#e38251;color:#fff;font-weight:900}.story-check li.passed{background:#e5f4ed}.story-check li.passed>span{background:#278768}.story-check p{margin:.2rem 0 0;font-size:.85rem}.submit-row{display:flex;justify-content:flex-end;gap:.7rem}.submitted-banner{padding:1rem;border-radius:.8rem;background:#dff2e8;color:#175944;font-weight:800}.feedback{border-left:6px solid #72599b}.feedback p{white-space:pre-wrap;margin:.5rem 0 0}@media(max-width:650px){.story-check ul{grid-template-columns:1fr}.editor-bar,.submit-row{flex-direction:column}.submit-row .btn{width:100%}}</style>
