<script setup lang="ts">
import AcademicNav from '@/Components/AcademicNav.vue'; import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import { Head, Link, useForm } from '@inertiajs/vue3'; const props=defineProps<{package?:any;providers:any[];frameworks:any[]}>(); const form=useForm({education_provider_id:props.package?.education_provider_id??null,standards_framework_id:props.package?.standards_framework_id??null,name:props.package?.name??'',version_label:props.package?.version_label??'',description:props.package?.description??'',status:props.package?.status??'draft',effective_start_date:props.package?.effective_start_date??'',effective_end_date:props.package?.effective_end_date??'',source_url:props.package?.source_url??''}); const submit=()=>props.package?form.patch(route('academic.curriculum.update',props.package.id)):form.post(route('academic.curriculum.store'));
</script>
<template><Head :title="package?'Edit Curriculum Package':'Create Curriculum Package'"/><AuthenticatedLayout><h1 class="h2">{{package?'Edit curriculum package':'Create draft curriculum package'}}</h1><AcademicNav/><form class="card" @submit.prevent="submit"><div class="card-body"><div class="row g-3">
<div class="col-md-8"><label for="package-name" class="form-label">Name</label><input id="package-name" v-model="form.name" class="form-control" required><div v-if="form.errors.name" class="invalid-feedback d-block">{{form.errors.name}}</div></div><div class="col-md-4"><label for="package-version" class="form-label">Version label</label><input id="package-version" v-model="form.version_label" class="form-control" required></div>
<div class="col-md-6"><label for="package-provider" class="form-label">Provider</label><select id="package-provider" v-model="form.education_provider_id" class="form-select"><option :value="null">No provider</option><option v-for="p in providers" :key="p.id" :value="p.id">{{p.name}}</option></select></div><div class="col-md-6"><label for="package-framework" class="form-label">Standards framework</label><select id="package-framework" v-model="form.standards_framework_id" class="form-select"><option :value="null">No framework</option><option v-for="f in frameworks" :key="f.id" :value="f.id">{{f.name}} · {{f.version_label}}</option></select></div>
<div class="col-md-4"><label for="package-status" class="form-label">Status</label><select id="package-status" v-model="form.status" class="form-select" :disabled="!package"><option v-for="s in ['draft','active','retired','archived']" :key="s">{{s}}</option></select><small v-if="!package" class="text-secondary">New packages always begin as drafts.</small></div><div class="col-md-4"><label for="package-start" class="form-label">Effective start</label><input id="package-start" v-model="form.effective_start_date" type="date" class="form-control"></div><div class="col-md-4"><label for="package-end" class="form-label">Effective end</label><input id="package-end" v-model="form.effective_end_date" type="date" class="form-control"></div>
<div class="col-12"><label for="package-url" class="form-label">Source URL</label><input id="package-url" v-model="form.source_url" type="url" class="form-control"></div><div class="col-12"><label for="package-description" class="form-label">Description</label><textarea id="package-description" v-model="form.description" class="form-control"/></div>
</div></div><div class="card-footer bg-white text-end"><Link class="btn btn-outline-secondary me-2" :href="route('academic.curriculum.index')">Cancel</Link><button class="btn btn-primary" :disabled="form.processing">Save package</button></div></form></AuthenticatedLayout></template>
