<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { formatDateOnly } from '@/Support/dateOnly';
import { Head, Link, usePage } from '@inertiajs/vue3';
defineProps<{ academy: any; schoolYear: any; students: any[]; setup: any; needsAttention: any[]; today: any; upcomingEvents: any[] }>();
const page = usePage<any>();
const canManageStudents = page.props.auth.permissions.includes('students.manage');
</script>
<template><Head title="Home" /><AuthenticatedLayout>
<header class="workspace-hero mb-4"><p class="text-uppercase small fw-semibold mb-1">Parent / Teacher Workspace</p><h1 class="display-6 mb-1">Welcome to {{ academy.name }}</h1><p class="mb-0 opacity-75">{{ schoolYear ? `${schoolYear.name} · ${formatDateOnly(schoolYear.start_date)} – ${formatDateOnly(schoolYear.end_date)}` : 'Start by choosing an active school year.' }}</p></header>
<div class="row g-4 mb-4"><section class="col-lg-8"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><h2 class="h4">Your students</h2><p class="text-secondary">The essentials for the active school year.</p></div><Link class="btn btn-sm btn-outline-primary align-self-start" :href="route('students.index')">View students</Link></div><div v-if="!students.length" class="empty-state py-4">No active students yet.</div><div v-else class="row g-3"><div v-for="student in students" :key="student.id" class="col-md-6"><Link class="student-summary text-decoration-none" :href="route('students.show', student.id)"><strong class="d-block text-body">{{ student.name }}</strong><span class="text-secondary">{{ student.enrollment ? `${student.enrollment.grade} · ${student.enrollment.school_year} · ${student.enrollment.status}` : 'Enrollment needed' }}</span><small class="d-block mt-2 text-capitalize">Student access: {{ student.access.status.replaceAll('_', ' ') }}<template v-if="student.access.username"> · {{ student.access.username }}</template></small><small class="d-block text-capitalize">Learning plan: {{ student.learning_plan_status.replaceAll('_', ' ') }}</small><small v-if="student.access.needs_password_change" class="d-block mt-2 text-warning-emphasis">{{ student.name }} needs to choose a new password at next login.</small></Link></div></div></div></div></section><section class="col-lg-4"><div class="card h-100"><div class="card-body"><h2 class="h4">Today</h2><p class="display-6 mb-1">{{ formatDateOnly(today.date) }}</p><p class="mb-0">{{ today.label }}</p></div></div></section></div>
<div class="row g-4 mb-4"><section class="col-lg-6"><div class="card h-100"><div class="card-body"><h2 class="h4">Get set up</h2><p class="text-secondary">{{ setup.completed }} of {{ setup.total }} essentials complete</p><div class="list-group list-group-flush"><Link v-for="item in setup.items" :key="item.key" class="list-group-item list-group-item-action px-0 d-flex gap-2" :href="route(item.route)"><span>{{ item.complete ? '✓' : '○' }}</span><span>{{ item.label }}</span></Link></div></div></div></section><section class="col-lg-6"><div class="card h-100"><div class="card-body"><h2 class="h4">Needs attention</h2><p v-if="!needsAttention.length" class="text-success mb-0">Nothing needs attention right now.</p><div v-else class="list-group list-group-flush"><Link v-for="item in needsAttention" :key="item.key" class="list-group-item list-group-item-action px-0" :href="route(item.route)"><strong class="d-block">{{ item.title }}</strong><small class="text-secondary">{{ item.detail }}</small></Link></div></div></div></section></div>
<div class="row g-4"><section class="col-lg-7"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><h2 class="h4">Upcoming dates</h2><Link :href="route('workspace.calendar')">Open calendar</Link></div><p v-if="!upcomingEvents.length" class="text-secondary mb-0">No upcoming school-calendar events have been added.</p><ul v-else class="list-group list-group-flush"><li v-for="event in upcomingEvents" :key="event.id" class="list-group-item px-0"><strong>{{ event.name }}</strong><span class="d-block text-secondary">{{ formatDateOnly(event.event_date) }}<template v-if="event.end_date"> – {{ formatDateOnly(event.end_date) }}</template></span></li></ul></div></div></section><section class="col-lg-5"><div class="card h-100"><div class="card-body"><h2 class="h4">Quick actions</h2><div class="d-grid gap-2"><Link v-if="students[0]" class="btn btn-primary" :href="route('students.show', students[0].id)">View {{ students[0].name }}</Link><Link v-if="canManageStudents && students[0]" class="btn btn-outline-primary" :href="route('students.access.show', students[0].id)">Manage student login</Link><Link class="btn btn-outline-secondary" :href="route('workspace.learning-plan')">Open learning plan</Link><Link class="btn btn-outline-secondary" :href="route('workspace.calendar')">View calendar</Link><Link class="btn btn-outline-secondary" :href="route('workspace.settings')">Continue setup</Link></div></div></div></section></div>
</AuthenticatedLayout></template>
