<script setup lang="ts">
import AcademicNav from '@/Components/AcademicNav.vue'; import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
const props = defineProps<{ calendar?: any; providers: any[]; defaults?: any }>();
const form = useForm({ education_provider_id: props.calendar?.education_provider_id ?? null, name: props.calendar?.name ?? '', academic_year_label: props.calendar?.academic_year_label ?? '', start_date: props.calendar?.start_date ?? '', end_date: props.calendar?.end_date ?? '', timezone: props.calendar?.timezone ?? props.defaults?.timezone ?? 'America/Chicago', status: props.calendar?.status ?? 'draft', source_type: props.calendar?.source_type ?? 'tenant_custom', source_url: props.calendar?.source_url ?? '', source_version: props.calendar?.source_version ?? '', notes: props.calendar?.notes ?? '' });
const submit = () => props.calendar ? form.patch(route('academic.calendars.update', props.calendar.id)) : form.post(route('academic.calendars.store'));
</script>
<template><Head :title="calendar ? 'Edit Calendar' : 'Add Calendar'" /><AuthenticatedLayout><h1 class="h2">{{ calendar ? 'Edit calendar profile' : 'Add calendar profile' }}</h1><AcademicNav />
<form class="card" @submit.prevent="submit"><div class="card-body"><div class="row g-3">
<div class="col-md-8"><label for="calendar-name" class="form-label">Name</label><input id="calendar-name" v-model="form.name" class="form-control" required :aria-describedby="form.errors.name ? 'calendar-name-error' : undefined"><div v-if="form.errors.name" id="calendar-name-error" class="invalid-feedback d-block">{{ form.errors.name }}</div></div>
<div class="col-md-4"><label for="calendar-label" class="form-label">Academic year label</label><input id="calendar-label" v-model="form.academic_year_label" class="form-control" placeholder="2026–2027"></div>
<div class="col-md-4"><label for="calendar-start" class="form-label">Start date</label><input id="calendar-start" v-model="form.start_date" type="date" class="form-control" required><div v-if="form.errors.start_date" class="invalid-feedback d-block">{{ form.errors.start_date }}</div></div>
<div class="col-md-4"><label for="calendar-end" class="form-label">End date</label><input id="calendar-end" v-model="form.end_date" type="date" class="form-control" required><div v-if="form.errors.end_date" class="invalid-feedback d-block">{{ form.errors.end_date }}</div></div>
<div class="col-md-4"><label for="calendar-timezone" class="form-label">Timezone</label><input id="calendar-timezone" v-model="form.timezone" class="form-control" required></div>
<div class="col-md-6"><label for="calendar-provider" class="form-label">Provider (optional)</label><select id="calendar-provider" v-model="form.education_provider_id" class="form-select"><option :value="null">No provider</option><option v-for="provider in providers" :key="provider.id" :value="provider.id">{{ provider.name }}{{ provider.tenant_id === null ? ' (shared)' : '' }}</option></select></div>
<div class="col-md-3"><label for="calendar-source" class="form-label">Source type</label><select id="calendar-source" v-model="form.source_type" class="form-select"><option v-for="type in ['tenant_custom','manual','provider','imported']" :key="type" :value="type">{{ type.replaceAll('_', ' ') }}</option></select></div>
<div class="col-md-3"><label for="calendar-status" class="form-label">Status</label><select id="calendar-status" v-model="form.status" class="form-select"><option v-for="status in ['draft','active','retired','archived']" :key="status">{{ status }}</option></select></div>
<div class="col-md-8"><label for="calendar-url" class="form-label">Source URL</label><input id="calendar-url" v-model="form.source_url" type="url" class="form-control"></div><div class="col-md-4"><label for="calendar-version" class="form-label">Source version</label><input id="calendar-version" v-model="form.source_version" class="form-control"></div>
<div class="col-12"><label for="calendar-notes" class="form-label">Notes</label><textarea id="calendar-notes" v-model="form.notes" class="form-control" rows="3" /></div>
</div></div><div class="card-footer bg-white text-end"><Link class="btn btn-outline-secondary me-2" :href="route('academic.calendars.index')">Cancel</Link><button class="btn btn-primary" :disabled="form.processing">{{ form.processing ? 'Saving…' : 'Save calendar' }}</button></div></form>
</AuthenticatedLayout></template>
