<script setup lang="ts">
import AcademicNav from '@/Components/AcademicNav.vue'; import CalendarEventRow from '@/Components/CalendarEventRow.vue'; import OwnershipBadge from '@/Components/OwnershipBadge.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import { formatDateOnly } from '@/Support/dateOnly';
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
const props = defineProps<{ calendar: any; summaries: any[]; linkedSources?: any[] }>(); const canManage = usePage<any>().props.auth.permissions.includes('calendars.manage') && !props.calendar.is_shared;
const form = useForm({ event_date: '', end_date: '', event_type: 'holiday', name: '', instructional_effect: 'non_instructional', status: 'active', notes: '', source_reference: '' });
const submit = () => form.post(route('academic.calendars.events.store', props.calendar.id), { preserveScroll: true, onSuccess: () => form.reset() });
</script>
<template><Head :title="calendar.name" /><AuthenticatedLayout>
<div class="d-flex justify-content-between mb-3"><div><h1 class="h2">{{ calendar.name }}</h1><p class="text-secondary">{{ formatDateOnly(calendar.start_date) }} – {{ formatDateOnly(calendar.end_date) }} · {{ calendar.timezone }}</p></div><div><OwnershipBadge :shared="calendar.is_shared" /> <Link v-if="canManage" class="btn btn-sm btn-outline-secondary ms-2" :href="route('academic.calendars.edit', calendar.id)">Edit profile</Link></div></div><AcademicNav />
<div class="d-flex flex-wrap gap-2 mb-3"><Link v-for="summary in summaries.filter((item) => item.compatible)" :key="summary.school_year_id" class="btn btn-outline-primary" :href="route('academic.overview', { school_year_id: summary.school_year_id })">Use in Academic Setup for {{ summary.school_year_name }}</Link><Link v-for="source in linkedSources ?? []" :key="source.id" class="btn btn-outline-secondary" :href="route('academic.sources.show', source.id)">View source: {{ source.title }}</Link></div>
<div class="row g-3 mb-4"><div v-for="summary in summaries" :key="summary.school_year_id" class="col-lg-6"><div class="card"><div class="card-body"><h2 class="h6">{{ summary.school_year_name }} calculated summary</h2><div class="row text-center"><div class="col"><strong>{{ summary.base_days }}</strong><small class="d-block">Base</small></div><div class="col"><strong>-{{ summary.removed_days }}</strong><small class="d-block">Removed</small></div><div class="col"><strong>+{{ summary.added_days }}</strong><small class="d-block">Added</small></div><div class="col"><strong>{{ summary.scheduled_days }}</strong><small class="d-block">Scheduled</small></div></div></div></div></div></div>
<form v-if="canManage" class="card mb-4" @submit.prevent="submit"><div class="card-body"><h2 class="h5">Add calendar event</h2><div class="row g-3">
<div class="col-md-6"><label for="event-name" class="form-label">Name</label><input id="event-name" v-model="form.name" class="form-control" required :aria-describedby="form.errors.name ? 'event-name-error' : undefined"><div v-if="form.errors.name" id="event-name-error" class="invalid-feedback d-block">{{ form.errors.name }}</div></div>
<div class="col-md-3"><label for="event-start" class="form-label">Start date</label><input id="event-start" v-model="form.event_date" type="date" class="form-control" required></div><div class="col-md-3"><label for="event-end" class="form-label">End date (optional)</label><input id="event-end" v-model="form.end_date" type="date" class="form-control"><div v-if="form.errors.end_date" class="invalid-feedback d-block">{{ form.errors.end_date }}</div></div>
<div class="col-md-6"><label for="event-type" class="form-label">Event type</label><select id="event-type" v-model="form.event_type" class="form-select"><option v-for="type in ['holiday','break','teacher_workday','staff_development','weather_closure','tenant_day_off','district_closure','instructional_makeup_day','instructional_override','other']" :key="type" :value="type">{{ type.replaceAll('_', ' ') }}</option></select></div>
<div class="col-md-6"><label for="event-effect" class="form-label">Instructional effect</label><select id="event-effect" v-model="form.instructional_effect" class="form-select"><option value="non_instructional">Non-instructional</option><option value="instructional">Instructional override</option><option value="informational">Informational only</option></select></div>
</div></div><div class="card-footer bg-white text-end"><button class="btn btn-primary" :disabled="form.processing">{{ form.processing ? 'Adding…' : 'Add event' }}</button></div></form>
<div class="card"><div class="card-body"><h2 class="h5">Calendar events</h2></div><div v-if="!calendar.events.length" class="empty-state">No events have been saved. Scheduled days currently equal base days.</div><div v-else class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Event</th><th>Date range</th><th>Effect</th><th>Status</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody><CalendarEventRow v-for="event in calendar.events" :key="event.id" :calendar-id="calendar.id" :event="event" :editable="canManage" /></tbody></table></div></div>
</AuthenticatedLayout></template>
