<script setup lang="ts">
const props = defineProps<{ modelValue: any; config: any; disabled?: boolean }>();
const emit = defineEmits<{ 'update:modelValue': [value: any] }>();
const update = (patch: any) => emit('update:modelValue', { ...props.modelValue, ...patch });
const toggleTerm = (term: string) => { const terms = props.modelValue.terms || []; update({ terms: terms.includes(term) ? terms.filter((item: string) => item !== term) : [...terms, term] }); };
const updateConnection = (index: number, key: string, value: string) => { const connections = JSON.parse(JSON.stringify(props.modelValue.connections || [])); connections[index][key] = value; update({ connections }); };
const connectionKey = (connection: any) => [connection.from, connection.relationship, connection.to].join('|');
const chooseConnection = (index: number, key: string) => { const selected = (props.config.allowed_connections || []).find((connection: any) => connectionKey(connection) === key) || { from: '', relationship: '', to: '' }; const connections = JSON.parse(JSON.stringify(props.modelValue.connections || [])); connections[index] = { ...selected }; update({ connections }); };
</script>

<template>
    <section class="systems-builder" aria-label="Digital Earth systems map builder">
        <fieldset :disabled="disabled"><legend>1. Choose at least {{ config.minimum_terms }} terms</legend><div class="term-grid"><label v-for="term in config.terms" :key="term"><input type="checkbox" :checked="modelValue.terms.includes(term)" @change="toggleTerm(term)"> {{ term }}</label></div></fieldset>
        <fieldset :disabled="disabled"><legend>2. Build at least {{ config.minimum_connections }} arrows</legend><div v-for="(_, index) in modelValue.connections" :key="index" class="connection-row"><select v-if="config.allowed_connections" :value="connectionKey(modelValue.connections[index])" @change="chooseConnection(index, ($event.target as HTMLSelectElement).value)"><option value="||">Choose an accurate connection</option><option v-for="connection in config.allowed_connections" :key="connectionKey(connection)" :value="connectionKey(connection)" :disabled="!modelValue.terms.includes(connection.from) || !modelValue.terms.includes(connection.to)">{{ connection.from }} → {{ connection.relationship }} → {{ connection.to }}</option></select><template v-else><select :value="modelValue.connections[index].from" @change="updateConnection(index, 'from', ($event.target as HTMLSelectElement).value)"><option value="">Choose a starting term</option><option v-for="term in modelValue.terms" :key="term" :value="term">{{ term }}</option></select><span>→</span><select :value="modelValue.connections[index].relationship" @change="updateConnection(index, 'relationship', ($event.target as HTMLSelectElement).value)"><option value="">Choose a relationship</option><option v-for="relation in config.relationships" :key="relation" :value="relation">{{ relation }}</option></select><span>→</span><select :value="modelValue.connections[index].to" @change="updateConnection(index, 'to', ($event.target as HTMLSelectElement).value)"><option value="">Choose an ending term</option><option v-for="term in modelValue.terms" :key="term" :value="term">{{ term }}</option></select></template></div></fieldset>
        <label class="question"><strong>3. What is one Earth-process question you want to investigate?</strong><textarea :value="modelValue.question" rows="2" maxlength="500" :disabled="disabled" @input="update({ question: ($event.target as HTMLTextAreaElement).value })" /></label>
        <div class="live-map" aria-live="polite"><strong>Your systems map</strong><p v-if="!modelValue.terms.length">Choose terms to begin.</p><div class="nodes"><span v-for="term in modelValue.terms" :key="term">{{ term }}</span></div><p v-for="(connection, index) in modelValue.connections.filter((item: any) => item.from && item.relationship && item.to)" :key="index"><b>{{ connection.from }}</b> → {{ connection.relationship }} → <b>{{ connection.to }}</b></p></div>
    </section>
</template>

<style scoped>
.systems-builder{display:grid;gap:1rem;margin:1rem 0}.systems-builder fieldset,.question,.live-map{border:2px solid #bfd8d3;border-radius:14px;padding:1rem}.systems-builder legend{font-weight:900}.term-grid{display:flex;flex-wrap:wrap;gap:.55rem}.term-grid label,.nodes span{padding:.5rem .75rem;border-radius:99px;background:#e0f3ef}.connection-row{display:grid;grid-template-columns:1fr;gap:.45rem;align-items:center;margin:.6rem 0}.connection-row select,.question textarea{width:100%;padding:.55rem;border:1px solid #91aaa9;border-radius:8px}.question{display:grid;gap:.5rem}.live-map{background:#f7fbfa}.nodes{display:flex;flex-wrap:wrap;gap:.45rem;margin:.7rem 0}.live-map p{margin:.4rem 0}
</style>
