<script setup lang="ts">
import AcademicNav from '@/Components/AcademicNav.vue'; import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import { Head, Link, useForm } from '@inertiajs/vue3';
const props=defineProps<{course?:any;subjects:any[];gradeLevels:any[];providers:any[];frameworks:any[]}>(); const form=useForm({subject_id:props.course?.subject_id??null,standards_framework_id:props.course?.standards_framework_id??null,education_provider_id:props.course?.education_provider_id??null,name:props.course?.name??'',code:props.course?.code??'',description:props.course?.description??'',minimum_grade_level_id:props.course?.minimum_grade_level_id??null,maximum_grade_level_id:props.course?.maximum_grade_level_id??null,status:props.course?.status??'draft'}); const submit=()=>props.course?form.patch(route('academic.courses.update',props.course.id)):form.post(route('academic.courses.store'));
</script>
<template><Head :title="course?'Edit Course':'Add Course'"/><AuthenticatedLayout><h1 class="h2">{{course?'Edit course':'Add course'}}</h1><AcademicNav/><form class="card" @submit.prevent="submit"><div class="card-body"><div class="row g-3">
<div class="col-md-8"><label for="course-name" class="form-label">Name</label><input id="course-name" v-model="form.name" class="form-control" required></div><div class="col-md-4"><label for="course-code" class="form-label">Code</label><input id="course-code" v-model="form.code" class="form-control" required><div v-if="form.errors.code" class="invalid-feedback d-block">{{form.errors.code}}</div></div>
<div class="col-md-4"><label for="course-subject" class="form-label">Subject</label><select id="course-subject" v-model="form.subject_id" class="form-select" required><option :value="null">Select subject</option><option v-for="s in subjects" :key="s.id" :value="s.id">{{s.name}}{{s.tenant_id===null?' (shared)':''}}</option></select><div v-if="form.errors.subject_id" class="invalid-feedback d-block">{{form.errors.subject_id}}</div></div>
<div class="col-md-4"><label for="course-min-grade" class="form-label">Minimum grade</label><select id="course-min-grade" v-model="form.minimum_grade_level_id" class="form-select"><option :value="null">All grades</option><option v-for="g in gradeLevels" :key="g.id" :value="g.id">{{g.name}}</option></select></div><div class="col-md-4"><label for="course-max-grade" class="form-label">Maximum grade</label><select id="course-max-grade" v-model="form.maximum_grade_level_id" class="form-select"><option :value="null">All grades</option><option v-for="g in gradeLevels" :key="g.id" :value="g.id">{{g.name}}</option></select><div v-if="form.errors.maximum_grade_level_id" class="invalid-feedback d-block">{{form.errors.maximum_grade_level_id}}</div></div>
<div class="col-md-6"><label for="course-provider" class="form-label">Provider reference</label><select id="course-provider" v-model="form.education_provider_id" class="form-select"><option :value="null">No provider</option><option v-for="p in providers" :key="p.id" :value="p.id">{{p.name}}</option></select></div><div class="col-md-6"><label for="course-framework" class="form-label">Standards framework</label><select id="course-framework" v-model="form.standards_framework_id" class="form-select"><option :value="null">No framework</option><option v-for="f in frameworks" :key="f.id" :value="f.id">{{f.name}} · {{f.version_label}}</option></select></div>
<div class="col-md-4"><label for="course-status" class="form-label">Status</label><select id="course-status" v-model="form.status" class="form-select"><option v-for="s in ['draft','active','retired','archived']" :key="s">{{s}}</option></select></div><div class="col-12"><label for="course-description" class="form-label">Description</label><textarea id="course-description" v-model="form.description" class="form-control"/></div>
</div></div><div class="card-footer bg-white text-end"><Link class="btn btn-outline-secondary me-2" :href="route('academic.courses.index')">Cancel</Link><button class="btn btn-primary" :disabled="form.processing">{{form.processing?'Saving…':'Save course'}}</button></div></form></AuthenticatedLayout></template>
